export default {
    API_ROOT:"http://localhost:3000",
    API_LOGIN:"http://localhost:3000/login",
    LOG_IN:"LOGGED_IN",
    LOG_OUT:"LOG_OUT",
    USER_INFO: "USER_INFO",
    FETCHING: "FETCHING",
    NEW_ERROR: "NEW_ERROR",
    CLEAR_ERRORS: "CLEAR_ERRORS",
    SET_USER_NEIGHBORHOODS: "SET_USER_NEIGHBORHOODS",
    SELECT_NEIGHBORHOOD: "SELECT_NEIGHBORHOOD",
    SET_SELECTED_NEIGHBORHOOD: "SET_SELECTED_NEIGHBORHOOD",
    UPDATE_ITEMS: "UPDATE_ITEMS",
    UPDATE_REQUESTS: "UPDATE_REQUESTS"
}